services:
  postgres-test:
    container_name: ${PROJECT_NAME}_postgres_test
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}-test
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/db/postgresql_test:/var/lib/postgresql/data
      - ./log/postgres_test:/var/log/postgres
    ports:
      - ${POSTGRES_TEST_PORT}:5432
    networks:
      app:
        ipv4_address: 172.28.1.3

  hoverfly-test:
    container_name: hoverfly-test
    image: spectolabs/hoverfly:${HOVERFLY_VERSION}
    command:
      - -webserver
    volumes:
      - ./app/hoverfly:/hoverfly_app:ro
    ports:
      - "8501:8501"
    networks:
      app:
        ipv4_address: ${HOVERFLY_TEST_IP}

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
