<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240515122331 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE book_to_book_category (book_id INT NOT NULL, book_category_id INT NOT NULL, PRIMARY KEY(book_id, book_category_id))');
        $this->addSql('CREATE INDEX IDX_57511BE216A2B381 ON book_to_book_category (book_id)');
        $this->addSql('CREATE INDEX IDX_57511BE240B1D29E ON book_to_book_category (book_category_id)');
        $this->addSql('ALTER TABLE book_to_book_category ADD CONSTRAINT FK_57511BE216A2B381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE book_to_book_category ADD CONSTRAINT FK_57511BE240B1D29E FOREIGN KEY (book_category_id) REFERENCES book_category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE book ADD slug VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE book ADD image VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE book ADD authors TEXT NOT NULL');
        $this->addSql('ALTER TABLE book ADD publication_date DATE NOT NULL');
        $this->addSql('ALTER TABLE book ADD meap BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE book ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE book_category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE book_to_book_category DROP CONSTRAINT FK_57511BE216A2B381');
        $this->addSql('ALTER TABLE book_to_book_category DROP CONSTRAINT FK_57511BE240B1D29E');
        $this->addSql('DROP TABLE book_to_book_category');
        $this->addSql('ALTER TABLE book DROP slug');
        $this->addSql('ALTER TABLE book DROP image');
        $this->addSql('ALTER TABLE book DROP authors');
        $this->addSql('ALTER TABLE book DROP publication_date');
        $this->addSql('ALTER TABLE book DROP meap');
        $this->addSql('ALTER TABLE book ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE book_category ALTER id DROP IDENTITY');
    }
}
